name: File Sync
schedule:
    - cron '20 16 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get files from main repo
        run: |
          git clone https://github.com/LegoManiac04/file-sync-source.git
          git clone https://github.com/LegoManiac04/file-sync.git
          cp file-sync-source/test/* file-sync/test
          sudo mv -f file-sync/test/* ./test
          sudo rm -R file-sync-source
          sudo rm -R file-sync


      - name: Setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "file-sync [bot]"
          git config user.email "<>"

      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated Files"
          git push

